(()=>{'use strict';if(window.esReadingReady)return;window.esReadingReady=true;
 const key='entre-saberes-font-scale';let scale=100;try{const n=Number(localStorage.getItem(key));if(Number.isFinite(n)&&n>=50&&n<=200)scale=n}catch{}
 let panel;function apply(value){scale=Math.max(50,Math.min(200,Math.round(Number(value)||100)));document.documentElement.style.setProperty('--es-scale',String(scale/100));document.documentElement.style.removeProperty('font-size');document.body.classList.toggle('es-large-text',scale>=140);if(panel){panel.querySelector('output').textContent=scale+'%';panel.querySelector('[data-summary-value]').textContent=scale+'%';panel.querySelector('input').value=scale;panel.querySelector('[data-change="-1"]').disabled=scale<=50;panel.querySelector('[data-change="1"]').disabled=scale>=200}try{localStorage.setItem(key,String(scale))}catch{}}
 function normalizeInline(){document.querySelectorAll('.rich-body [style*="font-size"],.lesson-content [style*="font-size"]').forEach(el=>{if(el.dataset.esFontNormalized)return;const f=el.style.fontSize;if(/^\d+(\.\d+)?px$/.test(f)){el.dataset.esFontNormalized='1';el.style.fontSize=(parseFloat(f)/16)+'rem'}})}
 function init(){panel=document.createElement('details');panel.className='es-reading-panel no-print';panel.innerHTML='<summary aria-label="Ajustar tamanho do texto">Aa <span data-summary-value>100%</span></summary><div class="es-reading-options"><label for="esFontRange">Tamanho do texto: 50% a 200%</label><input id="esFontRange" type="range" min="50" max="200" step="1" value="100"><div class="es-reading-row"><button type="button" data-change="-1" aria-label="Diminuir fonte em 1 ponto percentual">A\u2212</button><output for="esFontRange" class="es-reading-value" aria-live="polite">100%</output><button type="button" data-change="1" aria-label="Aumentar fonte em 1 ponto percentual">A+</button><button type="button" data-reset aria-label="Restaurar tamanho de 100%">100%</button></div><p class="es-reading-hint">Ajuste gradual de 1 em 1. A prefer\u00eancia fica salva neste navegador. O zoom do navegador continua dispon\u00edvel.</p></div>';
 panel.querySelector('input').addEventListener('input',e=>apply(e.target.value));panel.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-reset'))apply(100);else apply(scale+Number(b.dataset.change))});document.body.append(panel);
 const top=document.createElement('button');top.type='button';top.className='es-back-top no-print';top.textContent='\u2191';top.title='Voltar ao topo';top.setAttribute('aria-label','Voltar ao topo');top.onclick=()=>window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth'});document.body.append(top);const sync=()=>top.classList.toggle('is-visible',scrollY>350);addEventListener('scroll',sync,{passive:true});sync();apply(scale);normalizeInline();window.addEventListener('entre-saberes:article-loaded',normalizeInline);new MutationObserver(normalizeInline).observe(document.querySelector('main')||document.body,{childList:true,subtree:true});addEventListener('storage',e=>{if(e.key===key)apply(Number(e.newValue))});document.addEventListener('keydown',e=>{if(e.key==='Escape')panel.open=false});
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
