(()=>{
const cfg=window.ENTRE_SABERES_CONFIG;
if(!cfg||!window.supabase)return;
const lock=async(_n,_t,fn)=>await fn();
const sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false,storageKey:'entre-saberes-cms-auth-v19',lock}});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ret=()=>encodeURIComponent(location.href);
let enabled=false;
function adminLink(params){const q=new URLSearchParams(params);q.set('return',location.href);return `admin/?${q.toString()}`}
function addFloating(){if(document.querySelector('.es-edit-float'))return;const wrap=document.createElement('div');wrap.className='es-edit-float no-print';wrap.innerHTML='<span class="es-edit-mode">✎ Modo editor</span><a class="es-edit-main" href="admin/?view=dashboard" title="Abrir o painel administrativo">Painel</a>';document.body.appendChild(wrap)}
function addArticleEdit(){const host=document.querySelector('#articleHost');if(!host)return;const id=host.dataset.publicationId||new URLSearchParams(location.search).get('id');if(!id||document.querySelector('[data-direct-edit-publication]'))return;const a=document.createElement('a');a.dataset.directEditPublication=id;a.className='es-direct-edit button no-print';a.href=adminLink({edit:id});a.title='Editar esta publicação diretamente no CMS';a.textContent='✎ Editar publicação';const header=host.querySelector('.article-header');if(header)header.prepend(a);else host.prepend(a)}
function enhancePublicationCards(){document.querySelectorAll('.portal-post-card[data-publication-id]').forEach(card=>{if(card.querySelector('.es-card-edit'))return;const id=card.dataset.publicationId;if(!id)return;const a=document.createElement('a');a.className='es-card-edit no-print';a.href=adminLink({edit:id});a.title='Editar esta publicação no CMS';a.textContent='✎ Editar';card.appendChild(a)})}
function enhanceCourses(){document.querySelectorAll('.course-card[data-course-id]').forEach(card=>{if(card.querySelector('.es-card-edit'))return;const id=card.dataset.courseId;if(!id)return;const a=document.createElement('a');a.className='es-card-edit no-print';a.href=adminLink({course:id,view:'courses'});a.title='Editar este curso no CMS';a.textContent='✎ Editar curso';card.appendChild(a)})}
function enhanceEjatec(){document.querySelectorAll('.ejatec-item[data-ejatec-id]').forEach(card=>{if(card.querySelector('.es-card-edit'))return;const id=card.dataset.ejatecId;if(!id)return;const a=document.createElement('a');a.className='es-card-edit no-print';a.href=adminLink({ejatec:id,view:'ejatec'});a.title='Editar esta aula Aulas no CMS';a.textContent='✎ Editar aula';card.appendChild(a)})}
function contextualFloating(){const f=document.querySelector('.es-edit-float');if(!f)return;let href='',label='';const q=new URLSearchParams(location.search);const articleId=document.querySelector('#articleHost')?.dataset.publicationId||q.get('id');if(document.body.classList.contains('article-page')&&articleId){href=adminLink({edit:articleId});label='Editar publicação'}else if(document.body.dataset.learningPage==='courses'){href=adminLink({view:'courses'});label='Gerenciar cursos'}else if(document.body.dataset.learningPage==='coursepublic'){const cid=q.get('id');if(cid){href=adminLink({course:cid,view:'courses'});label='Editar curso'}}else if(document.body.dataset.learningPage==='ejatec'){href=adminLink({view:'ejatec'});label='Gerenciar Aulas'}if(href){let a=f.querySelector('.es-edit-context');if(!a){a=document.createElement('a');a.className='es-edit-context';f.appendChild(a)}a.href=href;a.textContent='✎ '+label;a.title=label}}
function scan(){if(!enabled)return;addFloating();addArticleEdit();enhancePublicationCards();enhanceCourses();enhanceEjatec();contextualFloating()}
async function boot(){try{const {data}=await sb.auth.getSession();const session=data?.session;if(!session)return;const {data:p,error}=await sb.from('profiles').select('papel,ativo').eq('id',session.user.id).maybeSingle();if(error||!p||p.ativo!==true||!['administrador','editor'].includes(p.papel))return;enabled=true;document.body.classList.add('es-editor-session');scan();new MutationObserver(scan).observe(document.body,{childList:true,subtree:true});window.addEventListener('entre-saberes:article-loaded',scan)}catch(e){console.warn('Modo editor indisponível:',e?.message||e)}}
boot();
})();
