(()=>{'use strict';
const q=(s,r=document)=>r.querySelector(s);
const text=(tag,value,className)=>{const e=document.createElement(tag);e.textContent=value;if(className)e.className=className;return e};
async function api(path,options={}){const r=await fetch(path,{...options,headers:{'content-type':'application/json',...options.headers},signal:AbortSignal.timeout(20000)});if(!r.headers.get('content-type')?.includes('application/json'))throw Error('O servidor desta funcionalidade ainda n\u00e3o foi publicado.');const data=await r.json();if(!r.ok)throw Error(data.error||'N\u00e3o foi poss\u00edvel concluir a solicita\u00e7\u00e3o.');return data}
function shareURL(){const u=new URL(location.href);for(const key of [...u.searchParams.keys()])if(!['id','slug'].includes(key))u.searchParams.delete(key);u.hash='';return u.href}
async function copy(value){if(navigator.clipboard&&isSecureContext){await navigator.clipboard.writeText(value);return}const t=document.createElement('textarea');t.value=value;t.style.cssText='position:fixed;top:0;left:0;opacity:0';document.body.append(t);t.select();const ok=document.execCommand('copy');t.remove();if(!ok)throw Error('Copie o endere\u00e7o pela barra do navegador.')}
function sharing(parent){
 const box=document.createElement('section');box.className='es-share no-print';box.setAttribute('aria-labelledby','esShareTitle');const heading=text('h2','Compartilhe este conhecimento');heading.id='esShareTitle';box.append(heading);
 const links=document.createElement('div');links.className='es-share-links';const url=shareURL(),title=document.querySelector('main h1')?.textContent?.trim()||document.title,enc=encodeURIComponent;
 const social=[['WhatsApp','https://api.whatsapp.com/send?text='+enc(title+' '+url)],['LinkedIn','https://www.linkedin.com/sharing/share-offsite/?url='+enc(url)],['Facebook','https://www.facebook.com/sharer/sharer.php?u='+enc(url)],['Telegram','https://t.me/share/url?url='+enc(url)+'&text='+enc(title)],['X','https://twitter.com/intent/tweet?url='+enc(url)+'&text='+enc(title)]];
 for(const [label,href] of social){const a=text('a',label);a.href=href;a.target='_blank';a.rel='noopener noreferrer';a.setAttribute('aria-label','Compartilhar no '+label+' (abre nova aba)');links.append(a)}
 const status=text('p','','es-share-status');status.setAttribute('role','status');
 const instagram=text('button','Instagram');instagram.type='button';instagram.title='Abrir o compartilhamento do dispositivo ou copiar o link';instagram.addEventListener('click',async()=>{try{if(navigator.share){await navigator.share({title,text:title,url});status.textContent='Compartilhamento encaminhado ao dispositivo. A escolha do aplicativo e o envio s\u00e3o seus.'}else{await copy(url);status.textContent='Link copiado. Cole-o na conversa, bio ou recurso de link do Instagram. O site n\u00e3o publica automaticamente.'}}catch(e){if(e.name!=='AbortError')status.textContent=e.message||'Compartilhamento indispon\u00edvel neste dispositivo.'}});links.append(instagram);
 const clip=text('button','Copiar link');clip.type='button';clip.addEventListener('click',async()=>{try{await copy(url);status.textContent='Link copiado.'}catch(e){status.textContent=e.message}});links.append(clip);
 box.append(links,text('p','No Instagram, o compartilhamento depende das op\u00e7\u00f5es oferecidas pelo seu dispositivo.','meta'),status);parent.append(box);
}
async function boot(){
 const host=q('#articleHost');if(!host?.dataset.publicationId||q('#esEngagement'))return;
 if(host.dataset.publicationStatus&&host.dataset.publicationStatus!=='publicado')return;
 const parent=document.createElement('div');parent.id='esEngagement';host.after(parent);sharing(parent);
 const box=document.createElement('section');box.className='es-comments no-print';box.id='comentarios';box.innerHTML=`<h2>Conversa sobre o texto</h2><p>Seu coment\u00e1rio ser\u00e1 exibido somente depois da aprova\u00e7\u00e3o da administra\u00e7\u00e3o. N\u00e3o publique dados pessoais sens\u00edveis.</p><div id="esCommentsList" aria-live="polite"></div><button id="esMoreComments" class="button secondary" type="button" hidden>Carregar mais coment\u00e1rios</button><h3>Deixe seu coment\u00e1rio</h3><form id="esCommentForm"><label>Nome que ser\u00e1 exibido<input name="author_name" minlength="2" maxlength="80" autocomplete="name" required></label><label>Coment\u00e1rio<textarea name="body" minlength="3" maxlength="3000" required></textarea></label><div class="es-honeypot" aria-hidden="true"><label>Website<input name="website" tabindex="-1" autocomplete="off"></label></div><label class="es-consent"><input type="checkbox" name="consent" required><span>Entendo que meu nome e meu coment\u00e1rio poder\u00e3o aparecer publicamente ap\u00f3s aprova\u00e7\u00e3o.</span></label><div id="esCaptcha"></div><button class="button" type="submit" disabled>Enviar para aprova\u00e7\u00e3o</button><p id="esCommentStatus" role="status">Verificando disponibilidade\u2026</p></form>`;parent.append(box);
 const form=q('form',box),message=q('#esCommentStatus',box),list=q('#esCommentsList',box),more=q('#esMoreComments',box);let offset=0,widget=null,config=null;
 async function load(append=false){try{const data=await api('/api/comments?publication='+encodeURIComponent(host.dataset.publicationId)+'&offset='+offset);if(!append)list.replaceChildren();if(!data.comments.length&&!append)list.append(text('p','Ainda n\u00e3o h\u00e1 coment\u00e1rios aprovados.'));for(const c of data.comments){const card=document.createElement('article');card.className='es-comment-card';const meta=document.createElement('header');meta.className='es-comment-meta';meta.append(text('strong',c.author_name),text('span',new Date(c.created_at).toLocaleDateString('pt-BR')));card.append(meta,text('p',c.body));list.append(card)}more.hidden=!data.has_more;}catch(e){if(!append)list.replaceChildren(text('p',e.message,'es-inline-notice'));else message.textContent=e.message}}
 more.addEventListener('click',async()=>{offset+=20;more.disabled=true;await load(true);more.disabled=false});load();
 try{config=await api('/api/config');if(!config.comments_configured)throw Error('Os coment\u00e1rios ainda precisam ser ativados pelo administrador no servidor.');if(config.turnstile_site_key){await new Promise((resolve,reject)=>{if(window.turnstile){resolve();return}const s=document.createElement('script');s.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';s.onload=resolve;s.onerror=()=>reject(Error('A verifica\u00e7\u00e3o antispam n\u00e3o carregou.'));document.head.append(s)});await new Promise(r=>window.turnstile.ready(r));widget=window.turnstile.render(q('#esCaptcha',box),{sitekey:config.turnstile_site_key,action:'comment'})}form.querySelector('[type=submit]').disabled=false;message.textContent='Seu e-mail e telefone n\u00e3o s\u00e3o solicitados neste formul\u00e1rio.'}catch(e){message.textContent=e.message;message.className='es-inline-notice';return}
 form.addEventListener('submit',async e=>{e.preventDefault();if(!form.reportValidity())return;const btn=form.querySelector('[type=submit]');btn.disabled=true;message.textContent='Enviando\u2026';const values=new FormData(form);try{const result=await api('/api/comments',{method:'POST',body:JSON.stringify({publication_id:host.dataset.publicationId,author_name:values.get('author_name'),body:values.get('body'),consent:values.has('consent'),website:values.get('website'),captcha_token:widget!==null?window.turnstile.getResponse(widget):null})});message.textContent=result.message;form.reset();if(widget!==null)window.turnstile.reset(widget)}catch(err){message.textContent=err.name==='TimeoutError'?'O envio n\u00e3o foi confirmado. Aguarde antes de tentar de novo.':err.message;if(widget!==null)window.turnstile.reset(widget)}finally{btn.disabled=false}});
}
window.addEventListener('entre-saberes:article-loaded',boot);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
