(()=>{
'use strict';
const cfg=window.ENTRE_SABERES_CONFIG;
if(!cfg||!window.supabase)return;
const sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false,storageKey:'entre-saberes-student-auth-v1'}});
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const q=new URLSearchParams(location.search);
const money=n=>Number(n||59.9).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function msg(t,err=false){const el=$('#pageMsg');if(el){el.textContent=t;el.className='meta '+(err?'status-error':'status-ok')}}
async function session(){const {data}=await sb.auth.getSession();return data?.session||null}
async function requireSession(){const s=await session();if(!s){location.href='login-aluno.html?next='+encodeURIComponent(location.pathname+location.search);throw new Error('login')}return s}
async function loadCourses(){const {data,error}=await sb.from('lms_courses').select('*').eq('status','publicado').order('criado_em',{ascending:false});if(error)throw error;return data||[]}
function courseCard(c,withQr=true){const href=`curso.html?id=${encodeURIComponent(c.id)}`;return `<article class="course-card clickable-course" data-course-id="${esc(c.id)}">
  <a class="course-card-main" href="${href}" aria-label="Conhecer o curso ${esc(c.titulo)}">
    ${c.imagem_url?`<img src="${esc(c.imagem_url)}" alt="">`:`<div class="course-placeholder" aria-hidden="true">🎓</div>`}
    <div class="course-card-copy"><span class="tag">Curso com certificado</span><h3>${esc(c.titulo)}</h3><p class="course-description">${esc(c.descricao||'Formação organizada em módulos, aulas, atividades e materiais de apoio.')}</p><div class="meta">Carga horária: ${esc(c.carga_horaria)} h • Certificado: ${c.certificado_ativo?'sim':'não'}</div><strong class="course-price">${money(59.90)}</strong><span class="course-open">Conhecer o curso →</span></div>
  </a>
  <div class="student-actions course-card-actions"><a class="button" href="cadastro-aluno.html?course=${encodeURIComponent(c.id)}">Quero este curso</a><a class="button secondary" href="login-aluno.html">Já sou aluno</a></div>
  ${withQr?`<div class="qr-box compact"><img src="pix-59-90.png" alt="QR Code Pix"><strong>${money(59.90)}</strong><small>Pix</small></div>`:''}
</article>`}
async function pageCourses(){const box=$('#courseCatalog');try{const rows=await loadCourses();box.innerHTML=rows.map(c=>courseCard(c,true)).join('')||'<div class="notice">Nenhum curso publicado ainda.</div>'}catch(e){console.error(e);box.innerHTML='<div class="notice">Não foi possível carregar os cursos agora. O catálogo continua salvo no Supabase; tente atualizar a página.</div>'}}
async function publicOutline(courseId){try{const {data,error}=await sb.rpc('public_course_outline',{p_course_id:courseId});if(error)return[];return data||[]}catch{return[]}}
async function pageCoursePublic(){const id=q.get('id');const host=$('#publicCourse');if(!id){host.innerHTML='<div class="notice">Curso não informado.</div>';return}const {data:c,error}=await sb.from('lms_courses').select('*').eq('id',id).eq('status','publicado').maybeSingle();if(error||!c){host.innerHTML='<div class="notice">Curso não encontrado ou ainda não publicado.</div>';return}document.title=`${c.titulo} — Entre Saberes`;$('#publicCourseTitle').textContent=c.titulo;$('#publicCourseDescription').textContent=c.descricao||'Formação organizada em módulos, aulas, atividades e materiais de apoio.';$('#publicCourseHours').textContent=`${c.carga_horaria} horas`;$('#publicCoursePrice').textContent=money(59.90);$('#publicCourseRegister').href=`cadastro-aluno.html?course=${encodeURIComponent(c.id)}`;const cover=$('#publicCourseCover');if(c.imagem_url){cover.src=c.imagem_url;cover.alt=c.titulo;cover.hidden=false}else cover.closest('.public-course-cover-wrap')?.classList.add('no-image');const rows=await publicOutline(c.id);const outline=$('#publicCourseOutline');if(!rows.length){outline.innerHTML='<div class="notice">A estrutura de módulos será exibida aqui à medida que o conteúdo do curso for publicado.</div>'}else{const mods=new Map();for(const r of rows){if(!mods.has(r.module_id))mods.set(r.module_id,{title:r.module_title,description:r.module_description,pos:r.module_position,lessons:[]});if(r.lesson_id)mods.get(r.module_id).lessons.push({id:r.lesson_id,title:r.lesson_title,pos:r.lesson_position})}outline.innerHTML=[...mods.values()].sort((a,b)=>a.pos-b.pos).map(m=>`<section class="public-module"><h3>${esc(m.title)}</h3>${m.description?`<p>${esc(m.description)}</p>`:''}<ul>${m.lessons.sort((a,b)=>a.pos-b.pos).map(l=>`<li>${esc(l.title)}</li>`).join('')}</ul></section>`).join('')}
  document.querySelector('#publicCourse')?.setAttribute('data-course-id',c.id);
}
async function pageRegister(){const select=$('#regCourse');let rows=[];try{rows=await loadCourses()}catch(e){msg('Não foi possível carregar os cursos: '+e.message,true);return}select.innerHTML='<option value="">Selecione...</option>'+rows.map(c=>`<option value="${c.id}">${esc(c.titulo)}</option>`).join('');if(q.get('course'))select.value=q.get('course');$('#studentForm').addEventListener('submit',async e=>{e.preventDefault();msg('Criando seu acesso...');const email=$('#regEmail').value.trim();const password=$('#regPassword').value;const confirm=$('#regConfirm').value;if(password!==confirm){msg('As senhas não coincidem.',true);return}const {data,error}=await sb.auth.signUp({email,password,options:{data:{full_name:$('#regName').value.trim()}}});if(error){msg(error.message,true);return}const payload={auth_user_id:data.user?.id||null,nome_completo:$('#regName').value.trim(),cpf:$('#regCpf').value.trim()||null,data_nascimento:$('#regBirth').value||null,email,whatsapp:$('#regPhone').value.trim()||null,cidade:$('#regCity').value.trim()||null,estado:$('#regState').value.trim()||null,course_id:select.value};const r=await sb.from('lms_access_requests').insert(payload);if(r.error){msg('Cadastro criado, mas a solicitação do curso falhou: '+r.error.message,true);return}$('#studentForm').hidden=true;$('#successBox').hidden=false;$('#successCourse').textContent=select.options[select.selectedIndex].textContent;})}
async function pageLogin(){const s=await session();if(s){location.href=q.get('next')||'meus-cursos.html';return}$('#studentLogin').addEventListener('submit',async e=>{e.preventDefault();msg('Entrando...');const {error}=await sb.auth.signInWithPassword({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value});if(error){msg(error.message,true);return}location.href=q.get('next')||'meus-cursos.html'})}
async function courseProgress(userId,courseId){const {data:mods}=await sb.from('lms_modules').select('id').eq('course_id',courseId);const mids=(mods||[]).map(x=>x.id);if(!mids.length)return{done:0,total:0,percent:0};const {data:lessons}=await sb.from('lms_lessons').select('id').in('module_id',mids).eq('publicado',true);const ids=(lessons||[]).map(x=>x.id);if(!ids.length)return{done:0,total:0,percent:0};const {data:done}=await sb.from('lms_progress').select('lesson_id').eq('user_id',userId).in('lesson_id',ids);const count=(done||[]).length;return{done:count,total:ids.length,percent:Math.round(count/ids.length*100)}}
async function pageMyCourses(){const s=await requireSession();$('#studentEmail').textContent=s.user.email;const {data,error}=await sb.from('lms_enrollments').select('id,status,matriculado_em,expira_em,lms_courses(*)').eq('user_id',s.user.id).in('status',['ativo','concluido']);if(error){msg(error.message,true);return}const box=$('#myCourses');if(!data?.length){box.innerHTML='<div class="notice">Você ainda não possui curso liberado. Após a confirmação do pagamento, o acesso é ativado pelo administrador.</div>';return}let html='';for(const e of data){const c=e.lms_courses;if(!c)continue;const progress=await courseProgress(s.user.id,c.id);html+=`<article class="card full"><span class="tag">${esc(e.status)}</span><h3>${esc(c.titulo)}</h3><p>${esc(c.descricao||'')}</p><div class="meta">Progresso: ${progress.percent}% • Carga horária: ${c.carga_horaria} h</div><div class="progress-track" style="margin:10px 0 16px"><div class="progress-bar" style="width:${progress.percent}%"></div></div><a class="button" href="curso-aluno.html?id=${c.id}">${progress.percent?'Continuar curso':'Iniciar curso'}</a></article>`}box.innerHTML=html||'<div class="notice">Nenhum curso ativo encontrado.</div>'}
async function checkEnrollment(userId,courseId){const {data}=await sb.from('lms_enrollments').select('*').eq('user_id',userId).eq('course_id',courseId).in('status',['ativo','concluido']).maybeSingle();return data||null}
async function pageCourse(){const s=await requireSession();const id=q.get('id');const enrollment=await checkEnrollment(s.user.id,id);if(!enrollment){$('#courseArea').innerHTML='<div class="container section"><div class="locked"><h2>Acesso não liberado</h2><p>Este curso ainda não está vinculado à sua conta.</p><a class="button" href="cursos.html">Ver catálogo</a></div></div>';return}const {data:c,error}=await sb.from('lms_courses').select('*').eq('id',id).single();if(error)return msg(error.message,true);$('#courseTitle').textContent=c.titulo;$('#courseDesc').textContent=c.descricao||'';const {data:mods}=await sb.from('lms_modules').select('*').eq('course_id',id).order('posicao');let nav='',content='';for(const m of mods||[]){const {data:ls}=await sb.from('lms_lessons').select('*').eq('module_id',m.id).eq('publicado',true).order('posicao');nav+=`<div class="lms-module"><div class="lms-module-title">${esc(m.titulo)}</div><div class="lms-lessons">${(ls||[]).map(l=>`<a href="aula.html?id=${l.id}">○ ${esc(l.titulo)}</a>`).join('')}</div></div>`;content+=`<article class="card full"><h3>${esc(m.titulo)}</h3><p>${esc(m.descricao||'')}</p><div class="content-list">${(ls||[]).map(l=>`<a class="content-item" href="aula.html?id=${l.id}"><strong>${esc(l.titulo)}</strong><span class="meta">Abrir aula →</span></a>`).join('')}</div></article>`}$('#moduleNav').innerHTML=nav||'<p>Nenhum módulo.</p>';$('#courseModules').innerHTML=content||'<div class="notice">O conteúdo deste curso está sendo preparado.</div>';const p=await courseProgress(s.user.id,id);$('#courseProgressText').textContent=`${p.done} de ${p.total} aulas concluídas (${p.percent}%)`;$('#courseProgressBar').style.width=p.percent+'%';if(p.total>0&&p.done>=p.total&&c.certificado_ativo)$('#certificateBtn').hidden=false;$('#certificateBtn').href=`certificado.html?course=${id}`}
async function pageLesson(){const s=await requireSession();const id=q.get('id');const {data:l,error}=await sb.from('lms_lessons').select('*,lms_modules(*,lms_courses(*))').eq('id',id).single();if(error)return msg(error.message,true);const c=l.lms_modules?.lms_courses;const enrollment=await checkEnrollment(s.user.id,c?.id);if(!enrollment){location.href='meus-cursos.html';return}$('#lessonCourse').textContent=c.titulo;$('#lessonTitle').textContent=l.titulo;$('#lessonContent').innerHTML=l.conteudo||'<p>Conteúdo em preparação.</p>';if(l.video_url)$('#lessonVideo').innerHTML=`<p><a class="button secondary" href="${esc(l.video_url)}" target="_blank" rel="noopener">Abrir vídeo da aula ↗</a></p>`;const {data:files}=await sb.from('lms_lesson_files').select('*').eq('lesson_id',id);const fbox=$('#lessonFiles');for(const f of files||[]){const {data:signed}=await sb.storage.from('course-files').createSignedUrl(f.storage_path,3600);if(signed?.signedUrl)fbox.insertAdjacentHTML('beforeend',`<a class="material-link" href="${signed.signedUrl}" target="_blank" rel="noopener">📎 ${esc(f.titulo)}</a>`)}const {data:acts}=await sb.from('lms_activities').select('*').eq('lesson_id',id).order('posicao');$('#lessonActivities').innerHTML=(acts||[]).map(a=>activityHtml(a)).join('');document.querySelectorAll('[data-submit-activity]').forEach(b=>b.onclick=()=>submitActivity(s.user.id,b.dataset.submitActivity,(acts||[]).find(x=>x.id===b.dataset.submitActivity)));const {data:done}=await sb.from('lms_progress').select('id').eq('user_id',s.user.id).eq('lesson_id',id).maybeSingle();const btn=$('#completeLesson');if(done){btn.textContent='✓ Aula concluída';btn.disabled=true}else btn.onclick=async()=>{const {error}=await sb.from('lms_progress').insert({user_id:s.user.id,lesson_id:id});if(error)msg(error.message,true);else{btn.textContent='✓ Aula concluída';btn.disabled=true;msg('Aula marcada como concluída.')}};$('#backCourse').href=`curso-aluno.html?id=${c.id}`}
function activityHtml(a){let input='';const opts=Array.isArray(a.opcoes)?a.opcoes:[];if(a.tipo==='multiple_choice'||a.tipo==='true_false')input=`<div class="activity-options">${opts.map(o=>`<label><input type="radio" name="act-${a.id}" value="${esc(o)}"> <span>${esc(o)}</span></label>`).join('')}</div>`;else if(a.tipo==='essay')input=`<textarea id="answer-${a.id}" rows="6" style="width:100%"></textarea>`;else input=`<input id="answer-${a.id}" style="width:100%;padding:10px" placeholder="Sua resposta">`;return `<section class="activity-box"><span class="tag">Atividade</span><h3>${esc(a.titulo)}</h3>${a.instrucoes?`<p>${esc(a.instrucoes)}</p>`:''}<p><strong>${esc(a.pergunta||'')}</strong></p>${input}<button class="button" type="button" data-submit-activity="${a.id}">Enviar resposta</button><p id="activity-msg-${a.id}" class="meta"></p></section>`}
async function submitActivity(userId,id,a){let answer='';if(a.tipo==='multiple_choice'||a.tipo==='true_false')answer=document.querySelector(`input[name="act-${id}"]:checked`)?.value||'';else answer=$(`#answer-${id}`)?.value||'';if(!answer)return;let score=null;if(['multiple_choice','true_false','short_answer'].includes(a.tipo)&&a.resposta_correta)score=answer.trim().toLowerCase()===String(a.resposta_correta).trim().toLowerCase()?100:0;const {error}=await sb.from('lms_submissions').upsert({user_id:userId,activity_id:id,resposta:answer,nota:score},{onConflict:'user_id,activity_id'});const el=$(`#activity-msg-${id}`);if(error)el.textContent=error.message;else el.textContent=score===null?'Resposta enviada para avaliação.':`Resposta enviada. Nota automática: ${score}%`}
async function pageCertificate(){const s=await requireSession();const courseId=q.get('course');const enrollment=await checkEnrollment(s.user.id,courseId);if(!enrollment){$('#certificateWrap').innerHTML='<div class="notice">Você não possui acesso a este curso.</div>';return}const {data:c}=await sb.from('lms_courses').select('*').eq('id',courseId).single();const p=await courseProgress(s.user.id,courseId);if(!p.total||p.done<p.total){$('#certificateWrap').innerHTML='<div class="notice">O certificado será liberado após a conclusão de todas as aulas.</div>';return}let cert=null;try{const r=await sb.rpc('student_issue_certificate',{p_course_id:courseId});if(!r.error)cert=Array.isArray(r.data)?r.data[0]:r.data}catch{}const name=cert?.student_name||s.user.user_metadata?.full_name||s.user.email;$('#certName').textContent=name;$('#certCourse').textContent=cert?.course_title||c.titulo;$('#certHours').textContent=(cert?.carga_horaria||c.carga_horaria)+' horas';$('#certDate').textContent=new Date(cert?.issued_at||Date.now()).toLocaleDateString('pt-BR');$('#certCode').textContent=cert?.token||('ES-'+enrollment.id.slice(0,8).toUpperCase()+'-'+courseId.slice(0,8).toUpperCase())}
async function pageEjatec(){const {data,error}=await sb.from('ejatec_lessons').select('*').eq('status','publicado').order('data_aula',{ascending:false}).order('posicao');if(error){msg(error.message,true);return}const box=$('#ejatecLessons');let html='';for(const l of data||[]){const {data:mats}=await sb.from('ejatec_materials').select('*').eq('lesson_id',l.id);const links=(mats||[]).map(m=>{const {data:u}=sb.storage.from('eja-tec').getPublicUrl(m.storage_path);return `<a class="material-link" href="${u.publicUrl}" target="_blank" rel="noopener">📎 ${esc(m.titulo)}</a>`}).join('');html+=`<article class="ejatec-item" data-ejatec-id="${esc(l.id)}"><div class="meta">${esc(l.disciplina||'Aulas')} ${l.turma?'• '+esc(l.turma):''} ${l.data_aula?'• '+new Date(l.data_aula+'T12:00:00').toLocaleDateString('pt-BR'):''}</div><h3>${esc(l.titulo)}</h3>${l.objetivo?`<p><strong>Objetivo:</strong> ${esc(l.objetivo)}</p>`:''}<div class="ejatec-content">${l.conteudo||''}</div>${l.atividade?`<div class="notice"><strong>Atividade:</strong><br>${esc(l.atividade)}</div>`:''}<div class="material-list">${links}</div></article>`}box.innerHTML=html||'<div class="notice">Ainda não há aulas publicadas em Aulas.</div>'}
async function logout(){await sb.auth.signOut();location.href='login-aluno.html'}
window.studentLogout=logout;
const page=document.body.dataset.learningPage;
({courses:pageCourses,coursepublic:pageCoursePublic,register:pageRegister,login:pageLogin,mycourses:pageMyCourses,course:pageCourse,lesson:pageLesson,certificate:pageCertificate,ejatec:pageEjatec}[page]||(()=>{}))().catch(e=>{if(e.message!=='login'){console.error(e);msg(e.message||String(e),true)}});
})();
