const PORTAL_CFG=window.ENTRE_SABERES_CONFIG;
const portalSb=window.supabase&&PORTAL_CFG?window.supabase.createClient(PORTAL_CFG.supabaseUrl,PORTAL_CFG.supabasePublishableKey):null;
const pEsc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const pType=v=>String(v||'conteúdo').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const pDate=v=>{try{return v?new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(v)):''}catch{return String(v||'')}};
function pKeywords(value){if(Array.isArray(value))return value.map(v=>String(v).trim()).filter(Boolean);if(value==null)return[];if(typeof value==='string'){const s=value.trim();if(!s)return[];try{const j=JSON.parse(s);if(Array.isArray(j))return j.map(v=>String(v).trim()).filter(Boolean)}catch{}return s.split(/[,;|]/).map(v=>v.trim()).filter(Boolean)}if(typeof value==='object')return Object.values(value).map(v=>String(v).trim()).filter(Boolean);return[String(value).trim()].filter(Boolean)}
function addGlobalSearch(){document.querySelectorAll('.site-header .nav').forEach(nav=>{if(nav.querySelector('.header-search-form'))return;const form=document.createElement('form');form.className='header-search-form';form.action='buscar.html';form.method='get';form.innerHTML='<label class="sr-only" for="headerSearch">Pesquisar no acervo</label><input id="headerSearch" name="q" type="search" placeholder="Pesquisar no acervo" aria-label="Pesquisar no acervo"><button type="submit" title="Pesquisar no acervo">⌕</button>';nav.appendChild(form)})}
function postCard(p){const keywords=pKeywords(p.palavras_chave).slice(0,3);const author=p.autor_nome?`<a class="card-author" href="autor.html?nome=${encodeURIComponent(p.autor_nome)}">${pEsc(p.autor_nome)}</a>`:'';const course=p.curso_nome?`<a class="card-course" href="programa.html?nome=${encodeURIComponent(p.curso_nome)}">${pEsc(p.curso_nome)}</a>`:'';return `<article class="portal-post-card${p.destaque?' is-featured':''}" data-publication-id="${pEsc(p.id)}">${p.imagem_capa?`<a class="portal-post-cover" href="article.html?id=${encodeURIComponent(p.id)}"><img src="${pEsc(p.imagem_capa)}" alt=""></a>`:''}<div class="portal-post-body"><div class="portal-post-kicker">${pEsc(p.modalidade_editorial||pType(p.tipo))}${p.publicado_em?` <span>•</span> ${pEsc(pDate(p.publicado_em))}`:''}</div><h3><a href="article.html?id=${encodeURIComponent(p.id)}">${pEsc(p.titulo)}</a></h3>${p.subtitulo?`<p class="portal-post-subtitle">${pEsc(p.subtitulo)}</p>`:''}${p.resumo?`<p>${pEsc(p.resumo)}</p>`:''}${(author||course)?`<div class="portal-post-byline">${author}${author&&course?' <span>•</span> ':''}${course}</div>`:''}${keywords.length?`<div class="portal-post-tags">${keywords.map(k=>`<a href="buscar.html?q=${encodeURIComponent(k)}" class="tag">${pEsc(k)}</a>`).join('')}</div>`:''}<a class="portal-read" href="article.html?id=${encodeURIComponent(p.id)}">Ler publicação →</a></div></article>`}
async function fetchPosts(limit=100){if(!portalSb)return[];const {data,error}=await portalSb.from('publications').select('*').order('publicado_em',{ascending:false}).limit(limit);if(error){console.warn('Entre Saberes:',error.message);throw error}return(data||[]).filter(p=>String(p.status||'').toLowerCase()==='publicado')}
function setHost(host,rows,empty='Nenhuma publicação disponível nesta seção.'){if(!host)return;host.innerHTML=rows.length?rows.map(postCard).join(''):`<div class="empty-state">${pEsc(empty)}</div>`}
function failHost(host,msg){if(host)host.innerHTML=`<div class="empty-state"><strong>Não foi possível carregar esta seção.</strong><br>${pEsc(msg||'Tente atualizar a página.')}</div>`}
async function loadHome(){const latest=document.querySelector('#latestPublications'),featured=document.querySelector('#featuredPublications');if(!latest&&!featured)return;try{const posts=await fetchPosts(60);if(latest)setHost(latest,posts.slice(0,6),'As primeiras publicações aparecerão aqui automaticamente.');if(featured){const rows=posts.filter(p=>p.destaque).slice(0,4);setHost(featured,rows.length?rows:posts.slice(0,4),'Nenhum conteúdo em destaque ainda.')}}catch(e){failHost(latest,e.message);failHost(featured,e.message)}}
async function loadTypedSections(){const memory=document.querySelector('#memoryPublications'),research=document.querySelector('#researchPublications'),library=document.querySelector('#libraryPublications');if(!memory&&!research&&!library)return;try{const posts=await fetchPosts(250);const tv=p=>String(p.tipo||'').toLowerCase().replaceAll(' ','_').normalize('NFD').replace(/[\u0300-\u036f]/g,'');if(memory)setHost(memory,posts.filter(p=>['memoria','historia_oral'].includes(tv(p))),'Ainda não há publicações de memória cadastradas.');if(research)setHost(research,posts.filter(p=>['artigo_cientifico','pesquisa','divulgacao_cientifica','ensaio','artigo'].includes(tv(p))),'Ainda não há publicações científicas cadastradas.');if(library)setHost(library,posts,'A biblioteca será preenchida automaticamente pelas publicações do CMS.')}catch(e){failHost(memory,e.message);failHost(research,e.message);failHost(library,e.message)}}
async function loadAuthor(){const host=document.querySelector('#authorPublications');if(!host)return;const name=new URLSearchParams(location.search).get('nome')||'';const title=document.querySelector('#authorName');if(title)title.textContent=name||'Autor';if(!name){setHost(host,[],'Autor não informado.');return}try{setHost(host,(await fetchPosts(500)).filter(p=>(p.autor_nome||'').toLocaleLowerCase('pt-BR')===name.toLocaleLowerCase('pt-BR')),'Nenhuma publicação encontrada para este autor.')}catch(e){failHost(host,e.message)}}
async function loadCourse(){const host=document.querySelector('#coursePublications');if(!host)return;const name=new URLSearchParams(location.search).get('nome')||'';const title=document.querySelector('#courseName');if(title)title.textContent=name||'Curso / programa';if(!name){setHost(host,[],'Curso não informado.');return}try{setHost(host,(await fetchPosts(500)).filter(p=>(p.curso_nome||'').toLocaleLowerCase('pt-BR')===name.toLocaleLowerCase('pt-BR')),'Nenhuma publicação vinculada a este curso ou programa.')}catch(e){failHost(host,e.message)}}
async function loadCategory(){const host=document.querySelector('#categoryPublications');if(!host||!portalSb)return;try{const slug=new URLSearchParams(location.search).get('slug')||'';const {data:cat,error:ce}=await portalSb.from('categories').select('id,nome,slug,descricao').eq('slug',slug).maybeSingle();if(ce)throw ce;const title=document.querySelector('#categoryName'),desc=document.querySelector('#categoryDescription');if(!cat){if(title)title.textContent='Categoria não encontrada';setHost(host,[],'Verifique o endereço da categoria ou use a pesquisa.');return}if(title)title.textContent=cat.nome;if(desc)desc.textContent=cat.descricao||'Publicações reunidas nesta área temática.';const {data:rels,error}=await portalSb.from('publication_categories').select('publication_id').eq('category_id',cat.id);if(error)throw error;const ids=(rels||[]).map(r=>r.publication_id);if(!ids.length){setHost(host,[],'Nenhuma publicação vinculada a esta categoria.');return}const {data:posts,error:pe}=await portalSb.from('publications').select('*').in('id',ids).order('publicado_em',{ascending:false});if(pe)throw pe;setHost(host,(posts||[]).filter(p=>String(p.status||'').toLowerCase()==='publicado'))}catch(e){failHost(host,e.message)}}
async function loadRelated(){const host=document.querySelector('#relatedPublications');if(!host)return;const id=new URLSearchParams(location.search).get('id');if(!id){host.closest('.related-section')?.remove();return}try{const posts=await fetchPosts(120),current=posts.find(p=>String(p.id)===String(id));if(!current){host.closest('.related-section')?.remove();return}const currentKeys=new Set(pKeywords(current.palavras_chave).map(k=>k.toLocaleLowerCase('pt-BR')));const scored=posts.filter(p=>String(p.id)!==String(id)).map(p=>{let score=0;if(p.tipo===current.tipo)score+=3;if(p.autor_nome&&p.autor_nome===current.autor_nome)score+=2;if(p.curso_nome&&p.curso_nome===current.curso_nome)score+=2;for(const k of pKeywords(p.palavras_chave))if(currentKeys.has(k.toLocaleLowerCase('pt-BR')))score+=1;return{p,score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,3).map(x=>x.p);if(!scored.length){host.closest('.related-section')?.remove();return}setHost(host,scored)}catch(e){host.closest('.related-section')?.remove();console.warn('Relacionados indisponíveis:',e.message)}}
addGlobalSearch();loadHome();loadTypedSections();loadAuthor();loadCourse();loadCategory();loadRelated();
