(()=>{'use strict';
 const body=document.body;if(!body||body.dataset.sidebarReady)return;body.dataset.sidebarReady='1';
 const items=[['\u2302','In\u00edcio','index.html'],['\u2315','Explorar','index.html#explorar'],['\u25eb','Saberes e Mem\u00f3rias','memorias.html'],['\u2301','Ci\u00eancia e Pesquisa','pesquisa.html'],['\u25a4','Biblioteca','biblioteca.html'],['\u2315','Pesquisa no acervo','buscar.html'],['\u2315','Pesquisa SciELO','pesquisa-scielo.html'],['\u25c6','Projeto','sobre.html'],['\u25a3','Cursos Livres','cursos.html'],['\u25a6','Aulas','aulas.html'],['\u2726','Teens Tech','teens-tech.html'],['\u265c','Senhores Professores','senhores-professores.html'],['\u2696','\u00d3tica do Estado','otica-do-estado.html'],['\u2659','\u00c1rea do Aluno','login-aluno.html']];
 let current=location.pathname.split('/').filter(Boolean).pop()||'index.html';if(!current.includes('.'))current+='.html';
 const side=document.createElement('aside');side.className='es-sidebar';side.id='esSidebar';side.setAttribute('aria-label','Navega\u00e7\u00e3o principal');
 side.innerHTML='<div class="es-sidebar-head"><button type="button" class="es-sidebar-toggle" aria-label="Recolher ou expandir menu" aria-controls="esSidebar">\u2630</button><a class="es-sidebar-brand" href="/index.html"><span class="es-sidebar-brand-short">ES</span><span class="es-sidebar-label">ENTRE SABERES</span></a></div><nav class="es-sidebar-nav"></nav><div class="es-sidebar-foot"><a class="es-side-link" href="/admin/" title="Administra\u00e7\u00e3o"><span class="es-side-icon">\u2699</span><span class="es-sidebar-label">Administra\u00e7\u00e3o</span></a></div>';
 const nav=side.querySelector('nav');items.forEach(([icon,label,href])=>{const a=document.createElement('a');a.href='/'+href;a.className='es-side-link';a.title=label;a.setAttribute('aria-label',label);const i=document.createElement('span');i.className='es-side-icon';i.setAttribute('aria-hidden','true');i.textContent=icon;const t=document.createElement('span');t.className='es-sidebar-label';t.textContent=label;a.append(i,t);if(href===current){a.classList.add('is-active');a.setAttribute('aria-current','page')}nav.append(a)});
 const overlay=document.createElement('button');overlay.type='button';overlay.className='es-sidebar-overlay';overlay.tabIndex=-1;overlay.setAttribute('aria-label','Fechar menu');
 const mobile=document.createElement('button');mobile.type='button';mobile.className='es-mobile-menu';mobile.textContent='\u2630';mobile.setAttribute('aria-label','Abrir menu de navega\u00e7\u00e3o');mobile.setAttribute('aria-controls','esSidebar');mobile.setAttribute('aria-expanded','false');body.prepend(overlay,side,mobile);body.classList.add('has-es-sidebar');
 const toggle=side.querySelector('button'),mq=matchMedia('(max-width:900px)'),storageKey='entreSaberesSidebarCollapsed';let previousFocus=null;
 const stored=()=>{try{return localStorage.getItem(storageKey)==='1'}catch{return false}};
 function open(value){body.classList.toggle('es-sidebar-mobile-open',value);side.inert=mq.matches&&!value;mobile.setAttribute('aria-expanded',String(value));toggle.setAttribute('aria-expanded',String(value));if(value){previousFocus=document.activeElement;toggle.focus()}else if(previousFocus&&mq.matches){previousFocus.focus();previousFocus=null}}
 function collapse(value){body.classList.toggle('es-sidebar-collapsed',value);toggle.setAttribute('aria-expanded',String(!value));try{localStorage.setItem(storageKey,value?'1':'0')}catch{}}
 function sync(){open(false);if(mq.matches)body.classList.remove('es-sidebar-collapsed');else{side.inert=false;body.classList.toggle('es-sidebar-collapsed',stored());toggle.setAttribute('aria-expanded',String(!stored()))}}
 mobile.onclick=()=>open(true);toggle.onclick=()=>mq.matches?open(false):collapse(!body.classList.contains('es-sidebar-collapsed'));overlay.onclick=()=>open(false);nav.addEventListener('click',()=>{if(mq.matches)open(false)});mq.addEventListener('change',sync);sync();
 document.addEventListener('keydown',e=>{if(!mq.matches||!body.classList.contains('es-sidebar-mobile-open'))return;if(e.key==='Escape'){open(false);return}if(e.key==='Tab'){const focus=[...side.querySelectorAll('a,button')].filter(el=>el.offsetParent!==null);const first=focus[0],last=focus.at(-1);if(e.shiftKey&&document.activeElement===first){last.focus();e.preventDefault()}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault()}}});
 const main=document.querySelector('main');if(main){if(!main.id)main.id='conteudo-principal';const skip=document.createElement('a');skip.href='#'+main.id;skip.className='es-skip-link';skip.textContent='Pular para o conte\u00fado';body.prepend(skip);const bar=document.createElement('div');bar.className='es-breadcrumb-bar no-print';const wrap=document.createElement('div');wrap.className='container es-breadcrumb-inner';const crumb=document.createElement('nav');crumb.className='es-global-breadcrumbs';crumb.setAttribute('aria-label','Trilha de navega\u00e7\u00e3o');
 const old=main.querySelector('.scientific-breadcrumb');if(old){while(old.firstChild)crumb.append(old.firstChild);old.remove()}else{const home=document.createElement('a');home.href='/index.html';home.textContent='In\u00edcio';crumb.append(home);if(current!=='index.html'){const sep=document.createElement('span');sep.textContent='\u203a';sep.setAttribute('aria-hidden','true');const cur=document.createElement('span');cur.id='esCurrentCrumb';cur.setAttribute('aria-current','page');cur.textContent=items.find(x=>x[2]===current)?.[1]||document.title.split('\u2014')[0].trim();crumb.append(sep,cur)}else home.setAttribute('aria-current','page')}
 wrap.append(crumb);bar.append(wrap);const header=document.querySelector('.site-header');if(header)header.after(bar);else main.before(bar);
 }
 window.addEventListener('entre-saberes:article-loaded',()=>{const c=document.getElementById('esCurrentCrumb');const title=document.querySelector('#articleHost h1');if(c&&title)c.textContent=title.textContent});
})();
