(()=>{'use strict';
const $=s=>document.querySelector(s),bridge=()=>window.ES40AdminBridge;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const STATUS={uploaded:'Aguardando envio/in\u00edcio',starting:'Iniciando no servidor',processing:'Em convers\u00e3o',ready:'Pronto para revisar',reviewing:'Revis\u00e3o salva',exported:'Incorporado \u00e0s publica\u00e7\u00f5es',error:'N\u00e3o conclu\u00eddo'};
let access=null,jobOffset=0,commentOffset=0,selected=null,dirty=false,sourceMode=false,timer=null,retryJob=null,busy=false;
const message=(id,s,error=false)=>{const e=$(id);if(e){e.textContent=s;e.classList.toggle('error',error)}};
const text=(tag,value,cls)=>{const e=document.createElement(tag);e.textContent=value;if(cls)e.className=cls;return e};
async function api(path,options={}){
 const b=bridge();if(!b?.client)throw Error('O painel n\u00e3o terminou de carregar. Entre novamente.');
 const {data,error}=await b.client.auth.getSession();if(error||!data?.session?.access_token)throw Error('Sess\u00e3o expirada. Entre novamente no painel.');
 const response=await fetch(path,{...options,headers:{'content-type':'application/json',authorization:'Bearer '+data.session.access_token,...options.headers},signal:AbortSignal.timeout(45000)});
 if(!response.headers.get('content-type')?.includes('application/json'))throw Error('As rotas da API V40 ainda n\u00e3o foram publicadas. Implante o Worker com ASSETS; somente enviar os arquivos HTML n\u00e3o ativa estes servi\u00e7os.');
 const result=await response.json();if(!response.ok){const err=Error(result.error||'Opera\u00e7\u00e3o n\u00e3o conclu\u00edda.');err.code=result.code;throw err}return result;
}
async function check(){
 $('#convSubmit').disabled=true;message('#convService','Conferindo a sess\u00e3o e a configura\u00e7\u00e3o do servidor\u2026');
 try{const state=await api('/api/admin/session');access=state.access;$('#convService').classList.toggle('warn',!state.converter_configured);$('#convService').textContent=state.converter_configured?'Sess\u00e3o editorial validada. Docling configurado; a conectividade e a convers\u00e3o ser\u00e3o verificadas no envio.':'Banco e sess\u00e3o validados. Falta configurar DOCLING_URL e DOCLING_API_KEY no Worker. Nenhum arquivo ser\u00e1 enviado enquanto isso.';$('#convSubmit').disabled=!state.converter_configured;return state}
 catch(e){$('#convService').classList.add('warn');message('#convService',e.message,true);return null}
}
function action(label,fn){const b=text('button',label,'button secondary');b.type='button';b.addEventListener('click',async()=>{b.disabled=true;try{await fn()}catch(e){message('#convUploadStatus',e.message,true)}finally{b.disabled=false}});return b}
async function jobs(){
 const list=$('#convJobs');list.textContent='Carregando hist\u00f3rico\u2026';
 try{const data=await api('/api/conversions?offset='+jobOffset);list.replaceChildren();if(!data.jobs.length)list.append(text('p','Nenhuma importa\u00e7\u00e3o nesta p\u00e1gina.'));
 for(const job of data.jobs){const card=document.createElement('article');card.className='es-job-card';card.append(text('h4',job.title),text('p',(STATUS[job.status]||job.status)+' \u00b7 '+new Date(job.created_at).toLocaleString('pt-BR')),text('p',job.original_name+' \u00b7 '+(job.bytes/1024/1024).toFixed(1)+' MB','meta'));if(job.error_message)card.append(text('p',job.error_message,'es-inline-notice'));
 const buttons=document.createElement('div');buttons.className='es-job-actions';
 if(['ready','reviewing','exported','processing','starting'].includes(job.status))buttons.append(action(job.status==='processing'||job.status==='starting'?'Acompanhar':'Abrir resultado',()=>openJob(job.id)));
 if(job.status==='uploaded'){buttons.append(action('Iniciar convers\u00e3o',()=>start(job.id)),action('Reenviar original',()=>{retryJob=job;$('#convRetryFile').value='';$('#convRetryFile').click()}),action('Descartar envio',async()=>{if(!confirm('Descartar este envio n\u00e3o iniciado?'))return;await api('/api/conversions/'+job.id+'/discard',{method:'POST',body:'{}'});await jobs()}))}
 if(job.status==='exported'&&job.publication_id){const link=text('a','Editar publica\u00e7\u00e3o','button secondary');link.href='?edit='+encodeURIComponent(job.publication_id);buttons.append(link)}
 card.append(buttons);list.append(card)}$('#convPrev').disabled=jobOffset===0;$('#convNext').disabled=!data.has_more;
 }catch(e){list.replaceChildren(text('p',e.message,'es-inline-notice error'));$('#convNext').disabled=true}
}
async function uploadFile(job,file){
 $('#convProgress').hidden=false;message('#convUploadStatus','Enviando o original para o armazenamento privado. Mantenha esta aba aberta at\u00e9 o envio terminar.');
 const {error}=await bridge().client.storage.from('apostilas').upload(job.storage_path,file,{contentType:job.mime_type,upsert:false,cacheControl:'3600'});
 if(error)throw Error('O envio n\u00e3o foi confirmado. Atualize o hist\u00f3rico para reenviar o original ou iniciar uma c\u00f3pia j\u00e1 recebida. '+(error.message||''));
 message('#convUploadStatus','Original enviado. Solicitando convers\u00e3o\u2026');await start(job.id);
}
async function start(id){const result=await api('/api/conversions/'+id+'/start',{method:'POST',body:'{}'});message('#convUploadStatus','Convers\u00e3o iniciada. Voc\u00ea poder\u00e1 retornar a esta conta para revisar o resultado.');await jobs();await openJob(result.id)}
$('#convUploadForm').addEventListener('submit',async e=>{e.preventDefault();if(!e.target.reportValidity()||busy)return;const file=$('#convFile').files[0];if(!file||file.size>30*1024*1024){message('#convUploadStatus','Selecione um arquivo de at\u00e9 30 MB.',true);return}busy=true;$('#convSubmit').disabled=true;$('#convProgress').hidden=false;try{const result=await api('/api/conversions',{method:'POST',body:JSON.stringify({title:$('#convTitle').value.trim(),name:file.name,bytes:file.size,ocr_mode:$('#convOCR').value,rights:$('#convRights').checked})});await uploadFile(result,file)}catch(err){message('#convUploadStatus',err.name==='TimeoutError'?'O servidor n\u00e3o confirmou o envio. Atualize o hist\u00f3rico antes de repetir.':err.message,true);await jobs()}finally{busy=false;$('#convProgress').hidden=true;$('#convSubmit').disabled=false}});
$('#convFile').addEventListener('change',()=>{const file=$('#convFile').files[0];if(file&&!$('#convTitle').value)$('#convTitle').value=file.name.replace(/\.[^.]+$/,'').replace(/[_-]/g,' ')});
$('#convRetryFile').addEventListener('change',async()=>{const file=$('#convRetryFile').files[0];if(!file||!retryJob)return;if(file.size!==retryJob.bytes){message('#convUploadStatus','Reenvie o mesmo original. O tamanho selecionado difere do registrado.',true);return}try{const {job}=await api('/api/conversions/'+retryJob.id);await uploadFile(job,file)}catch(e){message('#convUploadStatus',e.message,true)}finally{$('#convProgress').hidden=true;retryJob=null}});
function cleanLocal(html){if(!window.DOMPurify?.sanitize)throw Error('O editor visual n\u00e3o carregou a biblioteca de seguran\u00e7a. Use o c\u00f3digo HTML e a pr\u00e9-visualiza\u00e7\u00e3o isolada ou recarregue a p\u00e1gina.');return window.DOMPurify.sanitize(html,{USE_PROFILES:{html:true},FORBID_TAGS:['style','form','input','textarea','button','iframe','object','embed','template','video','audio'],FORBID_ATTR:['style','id','name','srcset']})}
function currentHTML(){return sourceMode?$('#convSource').value:$('#convVisual').innerHTML}
function editable(){return selected&&['ready','reviewing'].includes(selected.status)}
function buttons(){const ok=editable()&&!dirty&&$('#convReviewed').checked;$('#convDraft').disabled=!ok||busy;$('#convPublish').disabled=!ok||busy;$('#convReviewed').disabled=!editable()||dirty;$('#convSave').disabled=!editable()||busy;$('#convVisual').contentEditable=editable()?'true':'false';$('#convSource').readOnly=!editable()}
function markDirty(){if(!editable())return;dirty=true;$('#convReviewed').checked=false;$('#convPreview').hidden=true;buttons();message('#convReviewStatus','Altera\u00e7\u00f5es n\u00e3o salvas. Salve a revis\u00e3o antes de confirmar a publica\u00e7\u00e3o.')}
function chooseMode(source){if(source===sourceMode)return;try{if(source)$('#convSource').value=$('#convVisual').innerHTML;else $('#convVisual').innerHTML=cleanLocal($('#convSource').value);sourceMode=source;$('#convSource').hidden=!source;$('#convVisual').hidden=source;$('#convFormatBar').hidden=source;$('#convSourceTab').setAttribute('aria-pressed',String(source));$('#convVisualTab').setAttribute('aria-pressed',String(!source))}catch(e){message('#convReviewStatus',e.message,true)}}
async function openJob(id,refresh=false){
 if(!refresh&&dirty&&!confirm('H\u00e1 altera\u00e7\u00f5es n\u00e3o salvas. Deseja descart\u00e1-las para abrir este resultado?'))return;
 clearTimeout(timer);const {job}=await api('/api/conversions/'+id);selected=job;
 if(job.status==='processing'||job.status==='starting'){
  $('#convReview').hidden=true;message('#convUploadStatus',(STATUS[job.status]||job.status)+(job.task_position?' \u00b7 posi\u00e7\u00e3o na fila: '+job.task_position:'')+'. O resultado ainda n\u00e3o est\u00e1 dispon\u00edvel.');
  if(!document.hidden&&!$('#view-conversions').hidden)timer=setTimeout(()=>openJob(id,true).catch(e=>{message('#convUploadStatus',e.message,true);timer=setTimeout(()=>openJob(id,true).catch(()=>{}),15000)}),6000);return;
 }
 if(job.status==='error'){message('#convUploadStatus',job.error_message||'N\u00e3o foi poss\u00edvel converter este arquivo.',true);await jobs();return}
 if(!['ready','reviewing','exported'].includes(job.status))return;
 dirty=false;$('#convReview').hidden=false;$('#convEditTitle').value=job.title;$('#convAuthor').value=job.author_name;$('#convSummary').value=job.summary||'';$('#convCourse').value=job.course_name||'';$('#convReviewed').checked=false;$('#convWarnings').replaceChildren(...(Array.isArray(job.warnings)?job.warnings:[]).map(w=>text('p',w,'es-inline-notice')));$('#convSource').value=job.content_html||'';
 try{$('#convVisual').innerHTML=cleanLocal(job.content_html||'');sourceMode=true;chooseMode(false)}catch{$('#convVisual').replaceChildren();sourceMode=false;chooseMode(true);$('#convSource').value=job.content_html||''}
 $('#convPreview').hidden=true;$('#convPublishedLinks').replaceChildren();buttons();message('#convReviewStatus',job.status==='exported'?'Este resultado j\u00e1 foi incorporado ao portal. Novas altera\u00e7\u00f5es devem ser feitas na publica\u00e7\u00e3o vinculada.':'Resultado pronto. Compare com o original e confira a autoria antes de publicar.');if(job.publication_id)publishedLinks(job.publication_id);
 if(!refresh)$('#convReview').scrollIntoView({behavior:'smooth',block:'start'});await jobs();
}
function docHTML(title,html){const media=new URL(window.ENTRE_SABERES_CONFIG.supabaseUrl).origin;return '<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; img-src data: '+media+'; style-src \'unsafe-inline\'; base-uri \'none\'; form-action \'none\'"><title>'+esc(title)+'</title><style>*,*:before,*:after{box-sizing:border-box}body{margin:0;color:#20313d;background:#fff;font:18px/1.75 system-ui,sans-serif;overflow-wrap:break-word}main{width:calc(100% - 40px);max-width:900px;margin:40px auto}h1{font-size:clamp(2rem,6vw,3rem);line-height:1.15}h2,h3{line-height:1.3}img{max-width:100%;height:auto}figure{margin-inline:0}table{display:block;max-width:100%;overflow:auto;border-collapse:collapse}td,th{padding:8px;border:1px solid #cad7df}pre{white-space:pre-wrap;overflow-wrap:anywhere}a{color:#165c81}@media print{body{font-size:12pt}main{width:100%;margin:0}}</style></head><body><main><h1>'+esc(title)+'</h1>'+html+'</main></body></html>'}
$('#convVisualTab').addEventListener('click',()=>chooseMode(false));$('#convSourceTab').addEventListener('click',()=>chooseMode(true));
$('#convPreviewBtn').addEventListener('click',()=>{const frame=$('#convPreview');frame.srcdoc=docHTML($('#convEditTitle').value,currentHTML());frame.hidden=false;frame.scrollIntoView({behavior:'smooth',block:'nearest'})});
$('#convOriginal').addEventListener('click',async()=>{if(!selected)return;const tab=window.open('about:blank','_blank');if(tab)tab.opener=null;try{const data=await api('/api/conversions/'+selected.id+'/original');if(tab)tab.location.href=data.url;else{const link=text('a','Abrir original (acesso tempor\u00e1rio)','button secondary');link.href=data.url;link.target='_blank';link.rel='noopener noreferrer';$('#convPublishedLinks').append(link)}}catch(e){tab?.close();message('#convReviewStatus',e.message,true)}});
$('#convExportHTML').addEventListener('click',async()=>{if(!selected)return;if(dirty){message('#convReviewStatus','Salve a revis\u00e3o antes de baixar o HTML.',true);return}try{const {job}=await api('/api/conversions/'+selected.id);const blob=new Blob([docHTML(job.title,job.content_html)],{type:'text/html;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='apostila-'+job.id+'.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(e){message('#convReviewStatus',e.message,true)}});
for(const id of ['#convEditTitle','#convAuthor','#convCourse','#convSummary','#convVisual','#convSource'])$(id).addEventListener('input',markDirty);
$('#convVisual').addEventListener('paste',e=>{e.preventDefault();try{const html=e.clipboardData.getData('text/html');document.execCommand('insertHTML',false,html?cleanLocal(html):esc(e.clipboardData.getData('text/plain')).replace(/\n/g,'<br>'));markDirty()}catch(err){message('#convReviewStatus',err.message,true)}});
$('#convVisual').addEventListener('drop',e=>{e.preventDefault();message('#convReviewStatus','Para manter a seguran\u00e7a, use colar texto ou edite o HTML; n\u00e3o arraste arquivos para o conte\u00fado.')});
for(const b of document.querySelectorAll('[data-conv-format]')){b.addEventListener('mousedown',e=>e.preventDefault());b.addEventListener('click',()=>{if(!editable()||sourceMode)return;let value=null;if(b.dataset.convFormat==='createLink'){value=prompt('Endere\u00e7o completo (https://...)');if(!value||!/^https?:\/\//i.test(value))return}$('#convVisual').focus();document.execCommand(b.dataset.convFormat,false,value);markDirty()})}
$('#convBlock').addEventListener('change',e=>{if(!editable()||sourceMode)return;$('#convVisual').focus();document.execCommand('formatBlock',false,e.target.value);markDirty()});
$('#convReviewed').addEventListener('change',buttons);
async function save(){if(!editable())return;const title=$('#convEditTitle').value.trim(),author=$('#convAuthor').value.trim();if(title.length<2||author.length<2)throw Error('Informe t\u00edtulo e autoria.');const result=await api('/api/conversions/'+selected.id,{method:'PUT',body:JSON.stringify({revision:selected.revision,html:currentHTML(),title,author_name:author,summary:$('#convSummary').value,course_name:$('#convCourse').value})});selected.revision=result.revision;selected.status=result.status;dirty=false;$('#convReviewed').checked=false;message('#convReviewStatus','Revis\u00e3o salva. Confirme a revis\u00e3o para criar o rascunho ou publicar.'+(result.removed_images?' Algumas imagens externas foram removidas; reabra o resultado para conferir.':''));buttons();await jobs()}
$('#convSave').addEventListener('click',async()=>{if(busy)return;busy=true;buttons();try{await save()}catch(e){message('#convReviewStatus',e.message,true)}finally{busy=false;buttons()}});
function publishedLinks(id){const holder=$('#convPublishedLinks');holder.replaceChildren();const edit=text('a','Abrir publica\u00e7\u00e3o no editor','button secondary');edit.href='?edit='+encodeURIComponent(id);const view=text('a','Ver publica\u00e7\u00e3o / pr\u00e9via','button secondary');view.href='../article.html?id='+encodeURIComponent(id)+'&preview=1';view.target='_blank';view.rel='noopener noreferrer';holder.append(edit,view)}
async function publish(publishNow){if(!editable()||dirty||!$('#convReviewed').checked||busy)return;if(publishNow&&!confirm('Publicar "'+$('#convEditTitle').value+'" para todos os visitantes do portal?'))return;busy=true;buttons();try{const result=await api('/api/conversions/'+selected.id+'/publish',{method:'POST',body:JSON.stringify({revision:selected.revision,reviewed:true,publish:publishNow})});selected.status='exported';selected.publication_id=result.publication_id;message('#convReviewStatus',result.status==='publicado'?'Material publicado.':'Publica\u00e7\u00e3o criada em rascunho. Publique pelo editor quando estiver pronta.');publishedLinks(result.publication_id);await jobs()}catch(e){message('#convReviewStatus',e.name==='TimeoutError'?'A opera\u00e7\u00e3o n\u00e3o foi confirmada. Atualize o hist\u00f3rico antes de tentar novamente.':e.message,true)}finally{busy=false;buttons()}}
$('#convDraft').addEventListener('click',()=>publish(false));$('#convPublish').addEventListener('click',()=>publish(true));
$('#convCheck').addEventListener('click',check);$('#convRefresh').addEventListener('click',jobs);$('#convPrev').addEventListener('click',()=>{jobOffset=Math.max(0,jobOffset-20);jobs()});$('#convNext').addEventListener('click',()=>{jobOffset+=20;jobs()});
async function moderation(){
 const list=$('#commentsAdminList');list.textContent='Carregando\u2026';message('#commentsAdminStatus','');
 try{const data=await api('/api/admin/comments?status='+$('#commentsFilter').value+'&offset='+commentOffset);list.replaceChildren();if(!data.comments.length)list.append(text('p','Nenhum coment\u00e1rio nesta situa\u00e7\u00e3o e p\u00e1gina.'));
 for(const c of data.comments){const card=document.createElement('article');card.className='es-comment-card';const link=text('a',c.publications?.titulo||'Abrir publica\u00e7\u00e3o');link.href='../article.html?id='+encodeURIComponent(c.publication_id);link.target='_blank';link.rel='noopener noreferrer';card.append(link,text('h4',c.author_name),text('small',new Date(c.created_at).toLocaleString('pt-BR')),text('p',c.body));const row=document.createElement('div');row.className='es-job-actions';for(const [actionName,label] of [['approve','Aprovar'],['reject','Reprovar'],['delete','Excluir']]){if(actionName==='delete'&&!data.can_delete)continue;const b=text('button',label,'button secondary');b.type='button';b.addEventListener('click',async()=>{if(actionName==='delete'&&!confirm('Excluir definitivamente este coment\u00e1rio da lista?'))return;b.disabled=true;try{await api('/api/admin/comments/'+c.id,{method:'POST',body:JSON.stringify({action:actionName})});message('#commentsAdminStatus','Modera\u00e7\u00e3o registrada.');await moderation()}catch(e){message('#commentsAdminStatus',e.message,true);b.disabled=false}});row.append(b)}card.append(row);list.append(card)}$('#commentsPrev').disabled=commentOffset===0;$('#commentsNext').disabled=!data.has_more;
 }catch(e){list.replaceChildren();message('#commentsAdminStatus',e.message,true)}
}
$('#commentsRefresh').addEventListener('click',moderation);$('#commentsFilter').addEventListener('change',()=>{commentOffset=0;moderation()});$('#commentsPrev').addEventListener('click',()=>{commentOffset=Math.max(0,commentOffset-30);moderation()});$('#commentsNext').addEventListener('click',()=>{commentOffset+=30;moderation()});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)clearTimeout(timer);else if(selected?.status==='processing'&&!$('#view-conversions').hidden)openJob(selected.id,true).catch(e=>message('#convUploadStatus',e.message,true))});
window.ESAdmin40={async open(view){if(view==='conversions'){await check();await jobs()}else if(view==='comments')await moderation()}};
if(!$('#view-conversions').hidden)window.ESAdmin40.open('conversions');
})();
